// SULTAN Platform Seed Data — DEMO purposes only
// All data is fictional and tagged [DEMO]

export const categories = [
  { id: 'c-marketplace', nameAr: 'السوق', nameFr: 'Marketplace', nameEn: 'Marketplace', icon: 'Store', slug: 'marketplace', order: 0 },
  { id: 'c-electronics', nameAr: 'إلكترونيات', nameFr: 'Électronique', nameEn: 'Electronics', icon: 'Smartphone', slug: 'electronics', order: 1 },
  { id: 'c-furniture', nameAr: 'أثاث', nameFr: 'Meubles', nameEn: 'Furniture', icon: 'Armchair', slug: 'furniture', order: 2 },
  { id: 'c-fashion', nameAr: 'أزياء', nameFr: 'Mode', nameEn: 'Fashion', icon: 'Shirt', slug: 'fashion', order: 3 },
  { id: 'c-animals', nameAr: 'حيوانات', nameFr: 'Animaux', nameEn: 'Animals', icon: 'PawPrint', slug: 'animals', order: 4 },
  { id: 'c-hobbies', nameAr: 'هوايات', nameFr: 'Loisirs', nameEn: 'Hobbies', icon: 'Gamepad2', slug: 'hobbies', order: 5 },
  { id: 'c-motors', nameAr: 'السيارات', nameFr: 'Véhicules', nameEn: 'Motors', icon: 'Car', slug: 'motors', order: 6 },
  { id: 'c-realestate', nameAr: 'العقارات', nameFr: 'Immobilier', nameEn: 'Real Estate', icon: 'Building2', slug: 'realestate', order: 7 },
  { id: 'c-food', nameAr: 'الطعام', nameFr: 'Alimentation', nameEn: 'Food', icon: 'UtensilsCrossed', slug: 'food', order: 8 },
  { id: 'c-services', nameAr: 'الخدمات', nameFr: 'Services', nameEn: 'Services', icon: 'Wrench', slug: 'services', order: 9 },
  { id: 'c-jobs', nameAr: 'الوظائف', nameFr: 'Emploi', nameEn: 'Jobs', icon: 'Briefcase', slug: 'jobs', order: 10 },
  { id: 'c-auctions', nameAr: 'المزادات', nameFr: 'Enchères', nameEn: 'Auctions', icon: 'Gavel', slug: 'auctions', order: 11 },
  { id: 'c-charity', nameAr: 'التضامن', nameFr: 'Solidarité', nameEn: 'Charity', icon: 'Heart', slug: 'charity', order: 12 },
  { id: 'c-news', nameAr: 'الأخبار', nameFr: 'Actualités', nameEn: 'News', icon: 'Newspaper', slug: 'news', order: 13 },
  { id: 'c-zawaj', nameAr: 'الزواج والتعارف', nameFr: 'Mariage', nameEn: 'Zawaj & Taaruf', icon: 'HeartHandshake', slug: 'zawaj', order: 14 },
  { id: 'c-social', nameAr: 'السوشيال', nameFr: 'Social', nameEn: 'Social', icon: 'Users', slug: 'social', order: 15 },
];

export const cities = [
  { id: 'city-1', nameAr: 'الدار البيضاء', nameFr: 'Casablanca', nameEn: 'Casablanca', lat: 33.5731, lng: -7.5898 },
  { id: 'city-2', nameAr: 'الرباط', nameFr: 'Rabat', nameEn: 'Rabat', lat: 34.0209, lng: -6.8417 },
  { id: 'city-3', nameAr: 'مراكش', nameFr: 'Marrakech', nameEn: 'Marrakech', lat: 31.6295, lng: -7.9811 },
  { id: 'city-4', nameAr: 'فاس', nameFr: 'Fès', nameEn: 'Fez', lat: 34.0181, lng: -5.0078 },
  { id: 'city-5', nameAr: 'طنجة', nameFr: 'Tanger', nameEn: 'Tangier', lat: 35.7595, lng: -5.8340 },
  { id: 'city-6', nameAr: 'أكادير', nameFr: 'Agadir', nameEn: 'Agadir', lat: 30.4278, lng: -9.5981 },
  { id: 'city-7', nameAr: 'مكناس', nameFr: 'Meknès', nameEn: 'Meknes', lat: 33.8731, lng: -5.5407 },
  { id: 'city-8', nameAr: 'وجدة', nameFr: 'Oujda', nameEn: 'Oujda', lat: 34.6814, lng: -1.9086 },
  { id: 'city-9', nameAr: 'القنيطرة', nameFr: 'Kénitra', nameEn: 'Kenitra', lat: 34.2610, lng: -6.5802 },
  { id: 'city-10', nameAr: 'تطوان', nameFr: 'Tétouan', nameEn: 'Tetouan', lat: 35.5785, lng: -5.3684 },
  { id: 'city-11', nameAr: 'سلا', nameFr: 'Salé', nameEn: 'Sale', lat: 34.0531, lng: -6.7986 },
  { id: 'city-12', nameAr: 'تمارة', nameFr: 'Témara', nameEn: 'Temara', lat: 33.9280, lng: -6.9166 },
  { id: 'city-13', nameAr: 'الجديدة', nameFr: 'El Jadida', nameEn: 'El Jadida', lat: 33.2520, lng: -8.5045 },
  { id: 'city-14', nameAr: 'الناظور', nameFr: 'Nador', nameEn: 'Nador', lat: 35.1681, lng: -2.9287 },
  { id: 'city-15', nameAr: 'خريبكة', nameFr: 'Khouribga', nameEn: 'Khouribga', lat: 32.8844, lng: -6.9063 },
];

const profiles = [
  { id: 'p-1', displayName: 'يوسف بنعلي', avatar: 'https://ui-avatars.com/api/?name=%D9%8A%D9%88%D8%B3%D9%81%20%D8%A8%D9%86%D8%B9%D9%84%D9%8A&background=D4AF37&color=0A1628&bold=true&size=128', city: 'الدار البيضاء', isVerified: true, trustScore: 92, isSultanSupported: false, isRising: true },
  { id: 'p-2', displayName: 'فاطمة الزهراء العلوي', avatar: 'https://ui-avatars.com/api/?name=%D9%81%D8%A7%D8%B7%D9%85%D8%A9%20%D8%A7%D9%84%D8%B2%D9%87%D8%B1%D8%A7%D8%A1%20%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%8A&background=D4AF37&color=0A1628&bold=true&size=128', city: 'الرباط', isVerified: true, trustScore: 88, isSultanSupported: true, isRising: false },
  { id: 'p-3', displayName: 'كريم المنصوري', avatar: 'https://ui-avatars.com/api/?name=%D9%83%D8%B1%D9%8A%D9%85%20%D8%A7%D9%84%D9%85%D9%86%D8%B5%D9%88%D8%B1%D9%8A&background=D4AF37&color=0A1628&bold=true&size=128', city: 'مراكش', isVerified: false, trustScore: 65, isSultanSupported: false, isRising: true },
  { id: 'p-4', displayName: 'أمينة بوزيد', avatar: 'https://ui-avatars.com/api/?name=%D8%A3%D9%85%D9%8A%D9%86%D8%A9%20%D8%A8%D9%88%D8%B2%D9%8A%D8%AF&background=D4AF37&color=0A1628&bold=true&size=128', city: 'فاس', isVerified: true, trustScore: 95, isSultanSupported: false, isRising: false },
  { id: 'p-5', displayName: 'رشيد الفاسي', avatar: 'https://ui-avatars.com/api/?name=%D8%B1%D8%B4%D9%8A%D8%AF%20%D8%A7%D9%84%D9%81%D8%A7%D8%B3%D9%8A&background=D4AF37&color=0A1628&bold=true&size=128', city: 'طنجة', isVerified: true, trustScore: 78, isSultanSupported: false, isRising: true },
  { id: 'p-6', displayName: 'سارة بنحدو', avatar: 'https://ui-avatars.com/api/?name=%D8%B3%D8%A7%D8%B1%D8%A9%20%D8%A8%D9%86%D8%AD%D8%AF%D9%88&background=D4AF37&color=0A1628&bold=true&size=128', city: 'أكادير', isVerified: false, trustScore: 55, isSultanSupported: false, isRising: false },
  { id: 'p-7', displayName: 'محمد الإدريسي', avatar: 'https://ui-avatars.com/api/?name=%D9%85%D8%AD%D9%85%D8%AF%20%D8%A7%D9%84%D8%A5%D8%AF%D8%B1%D9%8A%D8%B3%D9%8A&background=D4AF37&color=0A1628&bold=true&size=128', city: 'الدار البيضاء', isVerified: true, trustScore: 90, isSultanSupported: true, isRising: false },
  { id: 'p-8', displayName: 'نورة التطوانية', avatar: 'https://ui-avatars.com/api/?name=%D9%86%D9%88%D8%B1%D8%A9%20%D8%A7%D9%84%D8%AA%D8%B7%D9%88%D8%A7%D9%86%D9%8A%D8%A9&background=D4AF37&color=0A1628&bold=true&size=128', city: 'تطوان', isVerified: false, trustScore: 60, isSultanSupported: false, isRising: true },
  { id: 'p-9', displayName: 'حمزة الرباطي', avatar: 'https://ui-avatars.com/api/?name=%D8%AD%D9%85%D8%B2%D8%A9%20%D8%A7%D9%84%D8%B1%D8%A8%D8%A7%D8%B7%D9%8A&background=D4AF37&color=0A1628&bold=true&size=128', city: 'الرباط', isVerified: true, trustScore: 82, isSultanSupported: false, isRising: false },
  { id: 'p-10', displayName: 'خديجة المراكشية', avatar: 'https://ui-avatars.com/api/?name=%D8%AE%D8%AF%D9%8A%D8%AC%D8%A9%20%D8%A7%D9%84%D9%85%D8%B1%D8%A7%D9%83%D8%B4%D9%8A%D8%A9&background=D4AF37&color=0A1628&bold=true&size=128', city: 'مراكش', isVerified: true, trustScore: 97, isSultanSupported: true, isRising: false },
  { id: 'p-11', displayName: 'عمر البيضاوي', avatar: 'https://ui-avatars.com/api/?name=%D8%B9%D9%85%D8%B1%20%D8%A7%D9%84%D8%A8%D9%8A%D8%B6%D8%A7%D9%88%D9%8A&background=D4AF37&color=0A1628&bold=true&size=128', city: 'الدار البيضاء', isVerified: false, trustScore: 45, isSultanSupported: false, isRising: false },
  { id: 'p-12', displayName: 'ليلى وجدية', avatar: 'https://ui-avatars.com/api/?name=%D9%84%D9%8A%D9%84%D9%89%20%D9%88%D8%AC%D8%AF%D9%8A%D8%A9&background=D4AF37&color=0A1628&bold=true&size=128', city: 'مكناس', isVerified: true, trustScore: 86, isSultanSupported: false, isRising: true },
];

const p = (i: number) => profiles[(i - 1) % profiles.length];

export const listings: any[] = [
  // === ELECTRONICS (50) ===
  { id: 'l-1', title: 'آيفون 15 برو ماكس 256GB', description: 'هاتف آيفون 15 برو ماكس لون تيتانيوم الطبيعي، 256 غيغابايت، حالة ممتازة مع جميع الملحقات الأصلية والعلبة. الجهاز استخدم لمدة 3 أشهر فقط ولا يوجد أي خدش. [DEMO]', price: 12400, currency: 'MAD', categoryId: 'c-electronics', condition: 'likeNew', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', status: 'active', viewsCount: 342, likesCount: 28, isFeatured: true, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-18T10:00:00Z', profile: p(1) },
  { id: 'l-2', title: 'سامسونغ جالكسي S24 Ultra', description: 'جالكسي S24 Ultra ذاكرته 512 غيغابايت لون تيتانيوم رمادي، مع قلم S Pen. الجهاز جديد لم يُفتح وضمان سنة كاملة من سامسونغ المغرب. [DEMO]', price: 13900, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1592899676301-95b3da6bd5d5?w=400&h=300&fit=crop', status: 'active', viewsCount: 567, likesCount: 45, isFeatured: true, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-17T14:30:00Z', profile: p(7) },
  { id: 'l-3', title: 'لابتوب ماك بوك برو M3', description: 'ماك بوك برو 14 بوصة بشريحة M3 Pro، ذاكرة 18GB، تخزين 512GB SSD. لونه فضائي رمادي وحالته ممتازة مع شاحن أصلي. مناسب للمصممين والمطورين. [DEMO]', price: 18500, currency: 'MAD', categoryId: 'c-electronics', condition: 'likeNew', city: 'الرباط', region: 'الرباط-سلا-القنيطرة', images: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', status: 'active', viewsCount: 289, likesCount: 19, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-16T09:00:00Z', profile: p(2) },
  { id: 'l-4', title: 'شاشة جيمنج 27 بوصة 165Hz', description: 'شاشة LG UltraGear 27 بوصة بدقة QHD ومعدل تحديث 165Hz، زمن استجابة 1ms، مزودة بتقنية HDR400. مثالية لألعاب البسي والتصميم. [DEMO]', price: 4200, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1592899676301-95b3da6bd5d5?w=400&h=300&fit=crop', status: 'active', viewsCount: 198, likesCount: 14, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-15T11:00:00Z', profile: p(5) },
  { id: 'l-5', title: 'بلايستيشن 5 مع ألعاب', description: 'بلايستيشن 5 نسخة الديسك مع ثلاثة ألعاب: سبايدرمان 2، جود أوف وار، وفورزا هورايزن. الجهاز بحالة ممتازة مع وحدة تحكم إضافية. [DEMO]', price: 4800, currency: 'MAD', categoryId: 'c-electronics', condition: 'used', city: 'مراكش', region: 'مراكش-آسفي', images: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', status: 'active', viewsCount: 456, likesCount: 38, isFeatured: true, isUrgent: true, negotiation: true, delivery: true, createdAt: '2026-08-19T08:00:00Z', profile: p(3) },
  { id: 'l-6', title: 'سماعات AirPods Pro 2', description: 'سماعات آبل AirPods Pro الجيل الثاني مع صندوق الشحن USB-C ونشطة إلغاء الضوضاء. جديدة لم تُستخدم مع ضمان سنة. [DEMO]', price: 2800, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'فاس', region: 'فاس-مكناس', images: 'https://images.unsplash.com/photo-1592899676301-95b3da6bd5d5?w=400&h=300&fit=crop', status: 'active', viewsCount: 234, likesCount: 16, isFeatured: false, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-14T16:00:00Z', profile: p(4) },
  { id: 'l-7', title: 'كاميرا سوني A7 IV عدسة 28-70mm', description: 'كاميرا ميرورلس سوني A7 IV بدقة 33 ميغابكسل مع عدسة كيت 28-70mm. مثالية للتصوير الاحترافي والفيديو مع فيديو 4K 60fps. [DEMO]', price: 22000, currency: 'MAD', categoryId: 'c-electronics', condition: 'likeNew', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', status: 'active', viewsCount: 156, likesCount: 11, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-13T10:00:00Z', profile: p(1) },
  { id: 'l-8', title: 'آيباد برو M2 12.9 بوصة', description: 'آيباد برو 12.9 بوصة بشريحة M2 وذاكرة 256GB مع Apple Pencil 2 ولوحة مفاتيح سحرية. الحالة ممتازة مع جميع الملحقات. [DEMO]', price: 11500, currency: 'MAD', categoryId: 'c-electronics', condition: 'used', city: 'الرباط', region: 'الرباط-سلا-القنيطرة', images: 'https://images.unsplash.com/photo-1592899676301-95b3da6bd5d5?w=400&h=300&fit=crop', status: 'active', viewsCount: 201, likesCount: 15, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-12T14:00:00Z', profile: p(9) },
  { id: 'l-9', title: 'ساعة آبل ووتش Ultra 2', description: 'ساعة Apple Watch Ultra 2 بحجم 49 مم مع سوار تايتانيوم. جديدة بالعلبة مع ضمان عامين من آبل. مقاومة للماء حتى 100 متر. [DEMO]', price: 8500, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'طنجة', region: 'طنجة-تطوان-الحسيمة', images: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', status: 'active', viewsCount: 178, likesCount: 12, isFeatured: false, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-11T09:00:00Z', profile: p(5) },
  { id: 'l-10', title: 'طابعة HP LaserJet Pro', description: 'طابعة ليزر متعددة الوظائف HP LaserJet Pro M404dn، طباعة مزدوجة الوجه، شبكة إيثرنت. مناسبة للمكاتب مع خرطوشة جديدة. [DEMO]', price: 3200, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1592899676301-95b3da6bd5d5?w=400&h=300&fit=crop', status: 'active', viewsCount: 89, likesCount: 5, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-10T11:00:00Z', profile: p(7) },
  { id: 'l-11', title: 'شاحن لابتوس عالمي 100W', description: 'شاحن لابتوس أوريكو 100 واط مع 4 منافذ USB-C يدعم الشحن السريع لجميع الأجهزة. صغير الحجم مناسب للسفر. [DEMO]', price: 350, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'أكادير', region: 'سوس-ماسة', images: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', status: 'active', viewsCount: 134, likesCount: 8, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-19T07:00:00Z', profile: p(6) },
  { id: 'l-12', title: 'مكبر صوت JBL Charge 5', description: 'مكبر صوت JBL Charge 5 مقاوم للماء مع بطارية تدوم 20 ساعة وصوت قوي 360 درجة. حالته ممتازة مع العلبة الأصلية. [DEMO]', price: 1800, currency: 'MAD', categoryId: 'c-electronics', condition: 'used', city: 'مراكش', region: 'مراكش-آسفي', images: 'https://images.unsplash.com/photo-1592899676301-95b3da6bd5d5?w=400&h=300&fit=crop', status: 'active', viewsCount: 167, likesCount: 13, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-09T15:00:00Z', profile: p(3) },
  { id: 'l-13', title: 'هارد ديسك خارجي 2TB SSD', description: 'هارد خارجي سامسونغ T7 Shield 2 تيرابايت SSD مقاوم للماء والصدمات مع سرعة نقل تصل إلى 1050 ميجابايت/ثانية. [DEMO]', price: 1500, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', status: 'active', viewsCount: 210, likesCount: 17, isFeatured: false, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-18T12:00:00Z', profile: p(1) },
  { id: 'l-14', title: 'لوحة مفاتيح ميكانيكية Logitech MX', description: 'لوحة مفاتيح لوجيتك MX Keys Mini لاسلكية مع إضاءة خلفية ذكية ومتعددة الأجهزة. مناسبة للعمل المكتبي. [DEMO]', price: 750, currency: 'MAD', categoryId: 'c-electronics', condition: 'likeNew', city: 'الرباط', region: 'الرباط-سلا-القنيطرة', images: 'https://images.unsplash.com/photo-1592899676301-95b3da6bd5d5?w=400&h=300&fit=crop', status: 'active', viewsCount: 98, likesCount: 6, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-17T10:00:00Z', profile: p(2) },
  { id: 'l-15', title: 'ماوس لوجيتك MX Master 3S', description: 'ماوس لاسلكي Logitech MX Master 3S مع تتبع مغناطيسي على أي سطح وعجلة تمرير سريعة. مثالي للمصممين والمبرمجين. [DEMO]', price: 850, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', status: 'active', viewsCount: 112, likesCount: 8, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-16T08:00:00Z', profile: p(7) },
  // More electronics
  { id: 'l-16', title: 'دراجة نارية هوندا CB500X 2024', description: 'دراجة نارية هوندا CB500X موديل 2024 لون أسود، 500 سي سي، قطعت 3200 كم فقط. بحالة الزيرو مع ضمان الوكالة. [DEMO]', price: 52000, currency: 'MAD', categoryId: 'c-electronics', condition: 'likeNew', city: 'طنجة', region: 'طنجة-تطوان-الحسيمة', images: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=400&h=300&fit=crop', status: 'active', viewsCount: 423, likesCount: 34, isFeatured: true, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-15T14:00:00Z', profile: p(5) },
  { id: 'l-17', title: 'تي في سامسونغ 55 بوصة QLED', description: 'شاشة تلفزيون سامسونغ 55 بوصة QLED 4K ذكية مع معالج Neural Quantum، مثالية للمشاهدة والألعاب. جديدة بالعلبة. [DEMO]', price: 6200, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1592899676301-95b3da6bd5d5?w=400&h=300&fit=crop', status: 'active', viewsCount: 189, likesCount: 10, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-14T09:00:00Z', profile: p(1) },
  { id: 'l-18', title: 'روتر Mesh WiFi 6E تي بي لينك', description: 'نظام شبكة Mesh من تي بي لينك WiFi 6E بثلاث وحدات لتغطية المنزل الكامل. سرعة تصل إلى 5.4 جيجابت. [DEMO]', price: 2400, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'فاس', region: 'فاس-مكناس', images: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', status: 'active', viewsCount: 76, likesCount: 4, isFeatured: false, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-13T11:00:00Z', profile: p(4) },
  { id: 'l-19', title: 'كاميرا مراقبة WiFi 4 قطع', description: 'طقم 4 كاميرات مراقبة لاسلكية بدقة 2K مع رؤية ليلية وتخزين سحابي. سهلة التركيب عبر تطبيق الجوال. [DEMO]', price: 1800, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'الرباط', region: 'الرباط-سلا-القنيطرة', images: 'https://images.unsplash.com/photo-1592899676301-95b3da6bd5d5?w=400&h=300&fit=crop', status: 'active', viewsCount: 145, likesCount: 9, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-12T10:00:00Z', profile: p(9) },
  { id: 'l-20', title: 'جهاز بروجكتور أبنوس 4K', description: 'بروجكتور أبنوس Q9 بدقة 4K مع 2000 لومن وسماعات مدمجة. مثالي للسينما المنزلية مع شاشة قابلة للطي 100 بوصة. [DEMO]', price: 4500, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'مراكش', region: 'مراكش-آسفي', images: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', status: 'active', viewsCount: 134, likesCount: 11, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-11T16:00:00Z', profile: p(10) },
  { id: 'l-21', title: 'هاتف شاومي 14 Ultra', description: 'شاومي 14 Ultra مع كاميرا لييكا رباعية ومعالج سنابدراغون 8 جين 3، ذاكرة 512 جيجابايت. جديد بالعلبة مع ضمان. [DEMO]', price: 9800, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1592899676301-95b3da6bd5d5?w=400&h=300&fit=crop', status: 'active', viewsCount: 278, likesCount: 21, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-10T09:00:00Z', profile: p(7) },
  { id: 'l-22', title: 'سماعات Sony WH-1000XM5', description: 'سماعات لاسلكية سوني فوق الأذن مع أفضل إلغاء ضوضاء في فئتها وبطارية تدوم 30 ساعة. جديدة مع ضمان. [DEMO]', price: 3200, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'طنجة', region: 'طنجة-تطوان-الحسيمة', images: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', status: 'active', viewsCount: 167, likesCount: 14, isFeatured: false, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-09T14:00:00Z', profile: p(5) },
  { id: 'l-23', title: 'بور بانك أنكر 24000mAh', description: 'بطارية خارجية أنكر 737 Power Bank بسعة 24000 مللي أمبير مع شحن سريع 140 واط ومنفذين USB-C. [DEMO]', price: 650, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'أكادير', region: 'سوس-ماسة', images: 'https://images.unsplash.com/photo-1592899676301-95b3da6bd5d5?w=400&h=300&fit=crop', status: 'active', viewsCount: 189, likesCount: 15, isFeatured: false, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-08T10:00:00Z', profile: p(6) },
  { id: 'l-24', title: 'درون DJI Mini 4 Pro', description: 'درون DJI Mini 4 Pro مع كاميرا 4K HDR ومستشعرات تجنب العوائق ومدة طيران 34 دقيقة. جديد بالعلبة مع ضمان. [DEMO]', price: 8500, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'مراكش', region: 'مراكش-آسفي', images: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', status: 'active', viewsCount: 234, likesCount: 19, isFeatured: false, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-07T11:00:00Z', profile: p(3) },
  { id: 'l-25', title: 'ماوس ديلقة لوجيتك G Pro X', description: 'ماوس جيمنج لوجيتك G Pro X Superlight 2 وزنه 60 غرام مع مستشعر HERO 2. مثالي لألعاب المنافسة. [DEMO]', price: 900, currency: 'MAD', categoryId: 'c-electronics', condition: 'likeNew', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1592899676301-95b3da6bd5d5?w=400&h=300&fit=crop', status: 'active', viewsCount: 145, likesCount: 10, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-06T15:00:00Z', profile: p(1) },
  // === FURNITURE (30) ===
  { id: 'l-26', title: 'طاولة سفرة مغربية صناعة يدوية', description: 'طاولة سفرة من خشب الأرز المغربي منحوتة يدويا بنقوش زليج أصيلة. مقاس 180x90 سم مع 6 كراسي مبطنة. قطعة فنية فريدة. [DEMO]', price: 12000, currency: 'MAD', categoryId: 'c-furniture', condition: 'new', city: 'مراكش', region: 'مراكش-آسفي', images: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop', status: 'active', viewsCount: 389, likesCount: 32, isFeatured: true, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-18T09:00:00Z', profile: p(10) },
  { id: 'l-27', title: 'أريكة حديثة 3 مقاعد', description: 'أريكة عصرية من القماش المخمل الرمادي مع وسائد إضافية. ثلاثة مقاعد بتصميم مينيمال يناسب الصالونات الحديثة. [DEMO]', price: 6500, currency: 'MAD', categoryId: 'c-furniture', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1493663244043-767b335930b8?w=400&h=300&fit=crop', status: 'active', viewsCount: 234, likesCount: 18, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-17T11:00:00Z', profile: p(1) },
  { id: 'l-28', title: 'خزانة ملابس 4 أبواب بمرآة', description: 'خزانة ملابس بتصميم عصري 4 أبواب مع مرآة كاملة ودرجين داخليين. من الخشب الميلامين عالي الجودة. التركيب مجاني. [DEMO]', price: 4800, currency: 'MAD', categoryId: 'c-furniture', condition: 'new', city: 'الرباط', region: 'الرباط-سلا-القنيطرة', images: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop', status: 'active', viewsCount: 178, likesCount: 14, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-16T14:00:00Z', profile: p(2) },
  { id: 'l-29', title: 'سرير كينج سايز مع مرتبة طبية', description: 'سرير خشبي كينج سايز مع لوح رأسي منجد ومرتبة طبية أوثوبيديك. التصميم كلاسيكي أنيق يناسب غرف النوم الفاخرة. [DEMO]', price: 8500, currency: 'MAD', categoryId: 'c-furniture', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1493663244043-767b335930b8?w=400&h=300&fit=crop', status: 'active', viewsCount: 267, likesCount: 20, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-15T10:00:00Z', profile: p(7) },
  { id: 'l-30', title: 'مكتب عمل خشب زيتون', description: 'مكتب عمل مصنوع من خشب الزيتون الأصيل بطابع مغربي تقليدي. مقاس 140x70 سم مع أدراج للتخزين. قطعة استثنائية. [DEMO]', price: 5500, currency: 'MAD', categoryId: 'c-furniture', condition: 'new', city: 'فاس', region: 'فاس-مكناس', images: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop', status: 'active', viewsCount: 156, likesCount: 12, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-14T09:00:00Z', profile: p(4) },
  { id: 'l-31', title: 'رف كتب جداري 2 متر', description: 'رف كتب من الخشب الطبيعي بارتفاع 2 متر وعرض 120 سم مع 6 أرفف قابلة للتعديل. تصميم سكاندنافي بسيط وأنيق. [DEMO]', price: 2200, currency: 'MAD', categoryId: 'c-furniture', condition: 'new', city: 'الرباط', region: 'الرباط-سلا-القنيطرة', images: 'https://images.unsplash.com/photo-1493663244043-767b335930b8?w=400&h=300&fit=crop', status: 'active', viewsCount: 123, likesCount: 8, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-13T08:00:00Z', profile: p(9) },
  { id: 'l-32', title: 'طاولة قهوة رخام أبيض', description: 'طاولة قهوة مستديرة قطر 80 سم من الرخام الأبيض مع قاعدة معدنية ذهبية. تصميم فاخر يضيف لمسة أناقة للصالون. [DEMO]', price: 3800, currency: 'MAD', categoryId: 'c-furniture', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop', status: 'active', viewsCount: 201, likesCount: 16, isFeatured: true, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-12T11:00:00Z', profile: p(1) },
  { id: 'l-33', title: 'طقم أثاث صالون كامل', description: 'طقم صالون كامل يشمل أريكة 3 مقاعد وأريكة 2 مقاعد وطاولة وسط وكرسي واحد. قماش مخمل مقاوم للبقع بألوان ترابية. [DEMO]', price: 18500, currency: 'MAD', categoryId: 'c-furniture', condition: 'new', city: 'مراكش', region: 'مراكش-آسفي', images: 'https://images.unsplash.com/photo-1493663244043-767b335930b8?w=400&h=300&fit=crop', status: 'active', viewsCount: 312, likesCount: 25, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-11T14:00:00Z', profile: p(3) },
  { id: 'l-34', title: 'ت chiffonnier 6 أدراج', description: 'تشيفونيير خشبي بتصميم عصري مع 6 أدراج واسعة ومقابض معدنية. لون أبيض كريمي يناسب جميع الديكورات. [DEMO]', price: 2800, currency: 'MAD', categoryId: 'c-furniture', condition: 'new', city: 'طنجة', region: 'طنجة-تطوان-الحسيمة', images: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop', status: 'active', viewsCount: 98, likesCount: 7, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-10T10:00:00Z', profile: p(5) },
  { id: 'l-35', title: 'مطبخ مودرن جاهز للتركيب', description: 'مطبخ مودرن كامل من الميلامين عالي الجودة مع رخام كوارتز وأجهزة مدمجة. يتضمن خزائن علوية وسفلية مع إضاءة LED. [DEMO]', price: 32000, currency: 'MAD', categoryId: 'c-furniture', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1493663244043-767b335930b8?w=400&h=300&fit=crop', status: 'active', viewsCount: 445, likesCount: 36, isFeatured: true, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-09T09:00:00Z', profile: p(7) },
  // === FASHION (25) ===
  { id: 'l-36', title: 'قفطان مغربي أصلي مطرز يدويا', description: 'قفطان نسائي فاخر من القماش الحريري مع تطريز يدوي بالخيوط الذهبية. من إنتاج حرفيي فاس. مناسب للمناسبات الكبرى والأعراس. [DEMO]', price: 4500, currency: 'MAD', categoryId: 'c-fashion', condition: 'new', city: 'فاس', region: 'فاس-مكناس', images: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop', status: 'active', viewsCount: 567, likesCount: 48, isFeatured: true, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-19T09:00:00Z', profile: p(4) },
  { id: 'l-37', title: 'جلباب رجالي فاخر', description: 'جلباب رجالي من القماش الأنجورا مع تطريز خفيف عند الياقة والأكمام. لون بيج فاتح مناسب لجميع المناسبات. [DEMO]', price: 1200, currency: 'MAD', categoryId: 'c-fashion', condition: 'new', city: 'مراكش', region: 'مراكش-آسفي', images: 'https://images.unsplash.com/photo-1525507119028-ed4c6290606d?w=400&h=300&fit=crop', status: 'active', viewsCount: 234, likesCount: 19, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-18T14:00:00Z', profile: p(10) },
  { id: 'l-38', title: 'حذاء نايكي أير ماكس 90', description: 'حذاء نايكي أير ماكس 90 كلاسيكي لون أبيض مع لمسات رمادية. مقاس 43 جديد بالعلبة مع فاتورة الشراء. [DEMO]', price: 1400, currency: 'MAD', categoryId: 'c-fashion', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop', status: 'active', viewsCount: 345, likesCount: 28, isFeatured: false, isUrgent: true, negotiation: true, delivery: true, createdAt: '2026-08-17T10:00:00Z', profile: p(1) },
  { id: 'l-39', title: 'حقيبة يد لوي فيتون مقلدة', description: 'حقيبة يد نسائية بتصميم كلاسيكي من الجلد الطبيعي مع بطانة قماشية. ليست أصلية لكنها عالية الجودة جدا. [DEMO]', price: 800, currency: 'MAD', categoryId: 'c-fashion', condition: 'new', city: 'طنجة', region: 'طنجة-تطوان-الحسيمة', images: 'https://images.unsplash.com/photo-1525507119028-ed4c6290606d?w=400&h=300&fit=crop', status: 'active', viewsCount: 289, likesCount: 22, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-16T11:00:00Z', profile: p(5) },
  { id: 'l-40', title: 'ساعة كاسيو G-Shock أصلية', description: 'ساعة كاسيو G-Shock GA-2100 مقاومة للصدمات والماء حتى 200 متر. لون أسود مع شاشة رقمية. جديدة بالضمان. [DEMO]', price: 1100, currency: 'MAD', categoryId: 'c-fashion', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop', status: 'active', viewsCount: 198, likesCount: 15, isFeatured: false, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-15T09:00:00Z', profile: p(7) },
  { id: 'l-41', title: 'نظارات شمسية راي بان أصلية', description: 'نظارات شمسية Ray-Ban Aviator Classic بنظارات خضراء كلاسيكية وإطار ذهبي. أصلية مع العلبة والمنشفة. [DEMO]', price: 1500, currency: 'MAD', categoryId: 'c-fashion', condition: 'new', city: 'أكادير', region: 'سوس-ماسة', images: 'https://images.unsplash.com/photo-1525507119028-ed4c6290606d?w=400&h=300&fit=crop', status: 'active', viewsCount: 167, likesCount: 13, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-14T14:00:00Z', profile: p(6) },
  { id: 'l-42', title: 'عباية نسائية مطرزة بالذهب', description: 'عباية سوداء فاخرة مطرزة بالخيوط الذهبية على الأكمام والياقة. قماش كريب ياباني عالي الجودة. [DEMO]', price: 2200, currency: 'MAD', categoryId: 'c-fashion', condition: 'new', city: 'الرباط', region: 'الرباط-سلا-القنيطرة', images: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop', status: 'active', viewsCount: 312, likesCount: 26, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-13T10:00:00Z', profile: p(2) },
  { id: 'l-43', title: 'بنطلون جينز ليفايز 501', description: 'بنطلون جينز ليفايز 501 كلاسيكي أزرق داكن مقاس 32. أصلي جديد بالملصق. قماش سميك متين يدوم طويلا. [DEMO]', price: 650, currency: 'MAD', categoryId: 'c-fashion', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1525507119028-ed4c6290606d?w=400&h=300&fit=crop', status: 'active', viewsCount: 178, likesCount: 11, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-12T09:00:00Z', profile: p(1) },
  // === VEHICLES (15) ===
  { id: 'l-44', title: 'دودج شارجر 2023 حالته ممتازة', description: 'دودج شارجر SXT موديل 2023 لون أسود، محرك V6 3.6 لتر، قطع 18000 كم. بحالة الزيرو مع جميع الصيانات في الوكالة. [DEMO]', price: 385000, currency: 'MAD', categoryId: 'c-motors', condition: 'likeNew', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=400&h=300&fit=crop', status: 'active', viewsCount: 890, likesCount: 67, isFeatured: true, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-19T08:00:00Z', profile: p(1) },
  { id: 'l-45', title: 'دياتس توبيار 2024 جديدة', description: 'دياتس توبيار موديل 2024 لون أبيض، محرك 1.6 لتر بنزين، ناقل أوتوماتيك. جديدة صفر من الوكالة مع ضمان 5 سنوات. [DEMO]', price: 175000, currency: 'MAD', categoryId: 'c-motors', condition: 'new', city: 'الرباط', region: 'الرباط-سلا-القنيطرة', images: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400&h=300&fit=crop', status: 'active', viewsCount: 567, likesCount: 42, isFeatured: true, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-18T10:00:00Z', profile: p(9) },
  { id: 'l-46', title: 'رينو كليو 5 موديل 2022', description: 'رينو كليو 5 لون رمادي، محرك تيربو 1.3 لتر، قطعت 32000 كم. بحالة ممتازة مع فحص تقني ساري المفعول. [DEMO]', price: 135000, currency: 'MAD', categoryId: 'c-motors', condition: 'used', city: 'مراكش', region: 'مراكش-آسفي', images: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=400&h=300&fit=crop', status: 'active', viewsCount: 423, likesCount: 31, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-17T14:00:00Z', profile: p(3) },
  { id: 'l-47', title: 'فولكسفاغن غولف 8 2023', description: 'فولكسفاغن غولف 8 لون أزرق، ديزل 2.0 TDI، قطع 24000 كم. بحالة ممتازة مع جميع الصيانات في الوكالة. [DEMO]', price: 295000, currency: 'MAD', categoryId: 'c-motors', condition: 'likeNew', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400&h=300&fit=crop', status: 'active', viewsCount: 345, likesCount: 25, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-16T09:00:00Z', profile: p(7) },
  { id: 'l-48', title: 'هيونداي توسان 2024', description: 'هيونداي توسان موديل 2024 لون رمادي ميتاليك، بنزين 1.6 تيربو، أوتوماتيك. جديدة مع ضمان 5 سنوات من الوكالة. [DEMO]', price: 245000, currency: 'MAD', categoryId: 'c-motors', condition: 'new', city: 'طنجة', region: 'طنجة-تطوان-الحسيمة', images: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=400&h=300&fit=crop', status: 'active', viewsCount: 456, likesCount: 34, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-15T11:00:00Z', profile: p(5) },
  // === REAL ESTATE (15) ===
  { id: 'l-49', title: 'شقة فاخرة في الدار البيضاء 3 غرف', description: 'شقة فاخرة 3 غرف وصالة كبيرة ومطبخ أمريكي في حي المعاريف. الطابق 7 مع مصعد وإطلالة على المحيط. مساحة 120م². [DEMO]', price: 9500, currency: 'MAD', categoryId: 'c-realestate', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1560518883-ce090597a0d0?w=400&h=300&fit=crop', status: 'active', viewsCount: 678, likesCount: 52, isFeatured: true, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-19T10:00:00Z', profile: p(7) },
  { id: 'l-50', title: 'فيلا ببرج صافي مع حديقة', description: 'فيلا مستقلة 4 غرف و3 حمامات مع حديقة 500م² وحمام سباحة. حي برج صافي الهادئ. مساحة 350م² مع تراس واسع. [DEMO]', price: 8500, currency: 'MAD', categoryId: 'c-realestate', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1512917774080-791f6a3f2f95?w=400&h=300&fit=crop', status: 'active', viewsCount: 890, likesCount: 71, isFeatured: true, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-18T11:00:00Z', profile: p(1) },
  { id: 'l-51', title: 'شقة للكراء في الرباط أغلويز', description: 'شقة 2 غرف وصالة في حي أغلويز، الطابق 3 مع مصعد. قريبة من المحطات والحوانيت. كراء شهري 4500 درهم. [DEMO]', price: 4500, currency: 'MAD', categoryId: 'c-realestate', condition: 'used', city: 'الرباط', region: 'الرباط-سلا-القنيطرة', images: 'https://images.unsplash.com/photo-1560518883-ce090597a0d0?w=400&h=300&fit=crop', status: 'active', viewsCount: 345, likesCount: 28, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-17T09:00:00Z', profile: p(9) },
  { id: 'l-52', title: 'أرض للبيع في مراكش 600م²', description: 'أرض مسطحة 600 متر مربع في منطقة تاملاشت قريبة من الطريق السيار. صالحة للبناء مع جميع الوثائق القانونية. [DEMO]', price: 1200000, currency: 'MAD', categoryId: 'c-realestate', condition: 'new', city: 'مراكش', region: 'مراكش-آسفي', images: 'https://images.unsplash.com/photo-1512917774080-791f6a3f2f95?w=400&h=300&fit=crop', status: 'active', viewsCount: 234, likesCount: 18, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-16T14:00:00Z', profile: p(3) },
  { id: 'l-53', title: 'محل تجاري في وسط الدار البيضاء', description: 'محل تجاري 80م² في شارع محمد الخامس مع واجهة زجاجية كبيرة. مناسب لأي نشاط تجاري. قريب من المواصلات العامة. [DEMO]', price: 12000, currency: 'MAD', categoryId: 'c-realestate', condition: 'used', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1560518883-ce090597a0d0?w=400&h=300&fit=crop', status: 'active', viewsCount: 456, likesCount: 35, isFeatured: false, isUrgent: true, negotiation: true, delivery: false, createdAt: '2026-08-15T10:00:00Z', profile: p(1) },
  // === FOOD/RESTAURANTS (10) ===
  { id: 'l-54', title: 'وجبة طاجين الدجاج بالزيتون', description: 'أشهى طاجين دجاج بالزيتون والليمون المصير يُقدم مع خبز الدار التقليدي. طعم أصلي مغربي من مطبخ أمينة الحرفي. التوصيل خلال 45 دقيقة. [DEMO]', price: 65, currency: 'MAD', categoryId: 'c-food', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop', status: 'active', viewsCount: 234, likesCount: 19, isFeatured: false, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-19T12:00:00Z', profile: p(4) },
  { id: 'l-55', title: 'كسكس الجمعة مع سبع خضروات', description: 'كسكس تقليدي مع سبع خضروات ولحم الغنم المذاب. يُحضر يوم الجمعة فقط بكميات محدودة. الطلب المسبق يُفضل. [DEMO]', price: 85, currency: 'MAD', categoryId: 'c-food', condition: 'new', city: 'فاس', region: 'فاس-مكناس', images: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop', status: 'active', viewsCount: 312, likesCount: 27, isFeatured: true, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-18T11:00:00Z', profile: p(4) },
  { id: 'l-56', title: 'باستيلا الدجاج باللوز', description: 'باستيلا فاسية أصيلة بالدجاج واللوز والقرفة مع ورق العجين الرقيق. حلوة ومالحة معا كما يجب أن تكون. [DEMO]', price: 75, currency: 'MAD', categoryId: 'c-food', condition: 'new', city: 'فاس', region: 'فاس-مكناس', images: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop', status: 'active', viewsCount: 267, likesCount: 22, isFeatured: false, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-17T14:00:00Z', profile: p(10) },
  // === SERVICES (10) ===
  { id: 'l-57', title: 'خدمة تنظيف منازل احترافية', description: 'فريق متخصص في تنظيف المنازل والشقق بالمنطقة البيضاوية. نستخدم مواد عضوية آمنة مع ضمان الرضا. خدمة يومية أو أسبوعية. [DEMO]', price: 300, currency: 'MAD', categoryId: 'c-services', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop', status: 'active', viewsCount: 189, likesCount: 12, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-19T09:00:00Z', profile: p(6) },
  { id: 'l-58', title: 'مصور أعراس محترف', description: 'تصوير فوتوغرافي وفيديو احترافي للأعراس والمناسبات. 8 سنوات خبرة مع أحدث المعدات. نسخ فلاش وكتاب ألبوم رقمي. [DEMO]', price: 5000, currency: 'MAD', categoryId: 'c-services', condition: 'new', city: 'مراكش', region: 'مراكش-آسفي', images: 'https://images.unsplash.com/photo-1521791136064-7986c662921e?w=400&h=300&fit=crop', status: 'active', viewsCount: 345, likesCount: 28, isFeatured: true, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-18T10:00:00Z', profile: p(3) },
  { id: 'l-59', title: 'دروس خصوصية في الرياضيات', description: 'أستاذ رياضيات ذو خبرة 15 سنة يقدم دروسا خصوصية لجميع المستويات من الابتدائي إلى الباكالوريا. نتائج مضمونة. [DEMO]', price: 150, currency: 'MAD', categoryId: 'c-services', condition: 'new', city: 'الرباط', region: 'الرباط-سلا-القنيطرة', images: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop', status: 'active', viewsCount: 234, likesCount: 16, isFeatured: false, isUrgent: false, negotiation: false, delivery: false, createdAt: '2026-08-17T11:00:00Z', profile: p(9) },
  { id: 'l-60', title: 'سباكة وصيانة منازل', description: 'فني سباكة معتمد يقدم خدمات الصيانة والإصلاح لجميع أنواع الأعطال. متاح 7 أيام في الأسبوع مع خدمة طوارئ. [DEMO]', price: 200, currency: 'MAD', categoryId: 'c-services', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1521791136064-7986c662921e?w=400&h=300&fit=crop', status: 'active', viewsCount: 167, likesCount: 10, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-16T09:00:00Z', profile: p(11) },
  // === JOBS (10) ===
  { id: 'l-61', title: 'مطور ويب Full-Stack', description: 'مطلوب مطور ويب Full-Stack ذو خبرة 3 سنوات على الأقل في React و Node.js. العمل حضوري في الدار البيضاء مع راتب مغري وضمان اجتماعي. [DEMO]', price: 15000, currency: 'MAD', categoryId: 'c-jobs', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop', status: 'active', viewsCount: 456, likesCount: 34, isFeatured: true, isUrgent: true, negotiation: false, delivery: false, createdAt: '2026-08-19T08:00:00Z', profile: p(7) },
  { id: 'l-62', title: 'مدير تسويق رقمي', description: 'شركة إعلانية مراكشية تبحث عن مدير تسويق رقمي لإدارة الحملات على السوشيال ميديا وجوجل. خبرة 5 سنوات مطلوبة. [DEMO]', price: 18000, currency: 'MAD', categoryId: 'c-jobs', condition: 'new', city: 'مراكش', region: 'مراكش-آسفي', images: 'https://images.unsplash.com/photo-1521791136064-7986c662921e?w=400&h=300&fit=crop', status: 'active', viewsCount: 312, likesCount: 22, isFeatured: false, isUrgent: false, negotiation: false, delivery: false, createdAt: '2026-08-18T14:00:00Z', profile: p(10) },
  { id: 'l-63', title: 'مصمم جرافيك فريلانسر', description: 'مطلوب مصمم جرافيك للعمل عن بعد على مشاريع متنوعة. إتقان أدوبي إليستريتور وفوتوشوب. الدفع حسب المشروع. [DEMO]', price: 500, currency: 'MAD', categoryId: 'c-jobs', condition: 'new', city: 'طنجة', region: 'طنجة-تطوان-الحسيمة', images: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop', status: 'active', viewsCount: 234, likesCount: 17, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-17T10:00:00Z', profile: p(5) },
  // === AUCTIONS ===
  { id: 'l-64', title: 'مقتنيات أثرية مغربية نادرة', description: 'مجموعة نادرة من المقتنيات الأثرية المغربية تشمل خنجر تقليدي مطعم بالذهب وعلبة بخور عودية قديمة. قيمتها التاريخية لا تقدر بثمن. [DEMO]', price: 15000, currency: 'MAD', categoryId: 'c-auctions', condition: 'used', city: 'فاس', region: 'فاس-مكناس', images: 'https://images.unsplash.com/photo-1560518883-ce090597a0d0?w=400&h=300&fit=crop', status: 'active', viewsCount: 567, likesCount: 45, isFeatured: true, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-19T07:00:00Z', profile: p(4) },
  { id: 'l-65', title: 'سجادة بربرية أصلية قديمة', description: 'سجادة بربرية منسوجة يدويا في جبال الأطلس عمرها أكثر من 50 سنة. قطعة فنية استثنائية بألوان طبيعية وزخارف تقليدية. [DEMO]', price: 8000, currency: 'MAD', categoryId: 'c-auctions', condition: 'used', city: 'مراكش', region: 'مراكش-آسفي', images: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop', status: 'active', viewsCount: 345, likesCount: 28, isFeatured: false, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-18T08:00:00Z', profile: p(3) },
  // === CHARITY ===
  { id: 'l-66', title: 'حملة إغاثة سكان الأطلس المتضررين', description: 'حملة لتوفير المساعدات الإنسانية لعائلات متضررة من الفيضانات في المناطق الجبلية. المبلغ يذهب مباشرة للمتضررين بشفافية كاملة. [DEMO]', price: 500000, currency: 'MAD', categoryId: 'c-charity', condition: 'new', city: 'مراكش', region: 'مراكش-آسفي', images: 'https://images.unsplash.com/photo-1521791136064-7986c662921e?w=400&h=300&fit=crop', status: 'active', viewsCount: 890, likesCount: 156, isFeatured: true, isUrgent: true, negotiation: false, delivery: false, createdAt: '2026-08-19T06:00:00Z', profile: p(10) },
  { id: 'l-67', title: 'جمعية تعليم الأطفال المحرومين', description: 'جمعية خيرية تهدف إلى توفير التعليم مجانا للأطفال في المناطق النائية. تبرعك يساعد في بناء فصل دراسي جديد. [DEMO]', price: 200000, currency: 'MAD', categoryId: 'c-charity', condition: 'new', city: 'الرباط', region: 'الرباط-سلا-القنيطرة', images: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop', status: 'active', viewsCount: 456, likesCount: 89, isFeatured: false, isUrgent: false, negotiation: false, delivery: false, createdAt: '2026-08-18T07:00:00Z', profile: p(2) },
  // More electronics
  { id: 'l-68', title: 'آيفون 14 برو 128GB', description: 'آيفون 14 برو لون أزرق داكن 128 غيغابايت بحالة ممتازة. مع الشاحن والكابل وبطاقة ضمان باقية 4 أشهر. [DEMO]', price: 8900, currency: 'MAD', categoryId: 'c-electronics', condition: 'used', city: 'أكادير', region: 'سوس-ماسة', images: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', status: 'active', viewsCount: 234, likesCount: 18, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-17T16:00:00Z', profile: p(6) },
  { id: 'l-69', title: 'لابتوب HP Pavilion 15', description: 'لابتوب HP Pavilion 15 بمعالج إنتل i5 الجيل 13 وذاكرة 8 جيجابايت وتخزين 256 SSD. مناسب للطلاب والموظفين. [DEMO]', price: 5500, currency: 'MAD', categoryId: 'c-electronics', condition: 'used', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1592899676301-95b3da6bd5d5?w=400&h=300&fit=crop', status: 'active', viewsCount: 178, likesCount: 11, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-16T15:00:00Z', profile: p(1) },
  { id: 'l-70', title: 'سماعات بلوتوث JBL Tune 770NC', description: 'سماعات لاسلكية فوق الأذن من JBL مع إلغاء الضوضاء النشط وبطارية تدوم 44 ساعة. جديدة بالعلبة. [DEMO]', price: 950, currency: 'MAD', categoryId: 'c-electronics', condition: 'new', city: 'الرباط', region: 'الرباط-سلا-القنيطرة', images: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop', status: 'active', viewsCount: 134, likesCount: 9, isFeatured: false, isUrgent: false, negotiation: false, delivery: true, createdAt: '2026-08-15T13:00:00Z', profile: p(9) },
  // More furniture
  { id: 'l-71', title: 'مكتبة خشبية كاملة الجدار', description: 'مكتبة خشبية بطول 3 أمتار وارتفاع 2.4 متر مع أدراج وأبواب. من خشب الصنوبر بتصميم كلاسيكي أنيق. [DEMO]', price: 4200, currency: 'MAD', categoryId: 'c-furniture', condition: 'new', city: 'فاس', region: 'فاس-مكناس', images: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop', status: 'active', viewsCount: 145, likesCount: 11, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-14T10:00:00Z', profile: p(4) },
  { id: 'l-72', title: 'سرير أطفال بطابقين', description: 'سرير أطفال بطابقين من الخشب المتين مع سلم آمن وحاجز حماية. يحتوي على درج للتخزين في الأسفل. [DEMO]', price: 3200, currency: 'MAD', categoryId: 'c-furniture', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1493663244043-767b335930b8?w=400&h=300&fit=crop', status: 'active', viewsCount: 189, likesCount: 14, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-13T14:00:00Z', profile: p(1) },
  // More fashion
  { id: 'l-73', title: 'جاكيت جلد طبيعي رجالي', description: 'جاكيت جلد طبيعي أسود بتصميم كلاسيكي. جلد بقري عالي الجودة مع بطانة حريرية. مناسب لفصل الشتاء. [DEMO]', price: 1800, currency: 'MAD', categoryId: 'c-fashion', condition: 'new', city: 'طنجة', region: 'طنجة-تطوان-الحسيمة', images: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop', status: 'active', viewsCount: 198, likesCount: 15, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-12T09:00:00Z', profile: p(5) },
  { id: 'l-74', title: 'حجاب قطني فاخر 5 قطع', description: 'طقم 5 حجابات قطنية فاخرة بألوان متعددة. قماش ناعم ومريح مع تطريز خفيف. مناسبة للاستخدام اليومي. [DEMO]', price: 250, currency: 'MAD', categoryId: 'c-fashion', condition: 'new', city: 'فاس', region: 'فاس-مكناس', images: 'https://images.unsplash.com/photo-1525507119028-ed4c6290606d?w=400&h=300&fit=crop', status: 'active', viewsCount: 267, likesCount: 21, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-11T10:00:00Z', profile: p(4) },
  // More vehicles
  { id: 'l-75', title: 'بيجو 208 موديل 2023', description: 'بيجو 208 لون أحمر، بنزين 1.2 لتر، أوتوماتيك. قطعت 15000 كم بحالة ممتازة. صيانة وكالة منتظمة. [DEMO]', price: 165000, currency: 'MAD', categoryId: 'c-motors', condition: 'used', city: 'أكادير', region: 'سوس-ماسة', images: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400&h=300&fit=crop', status: 'active', viewsCount: 289, likesCount: 21, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-14T10:00:00Z', profile: p(6) },
  { id: 'l-76', title: 'فورد رينجر 2024 دبل كابينة', description: 'شاحنة فورد رينجر دبل كابينة 2024 لون أبيض، ديزل 2.0 Bi-Turbo. جديدة بالضمان مع جميع التجهيزات. [DEMO]', price: 420000, currency: 'MAD', categoryId: 'c-motors', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=400&h=300&fit=crop', status: 'active', viewsCount: 345, likesCount: 26, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-13T11:00:00Z', profile: p(1) },
  // More real estate
  { id: 'l-77', title: 'استوديو مفروش بالرباط', description: 'استوديو مفروش بالكامل 35م² في حي الحسن للطلاب. يتضمن سرير وأثاث ومطبخ صغير. قريب من الجامعات والمواصلات. [DEMO]', price: 3000, currency: 'MAD', categoryId: 'c-realestate', condition: 'used', city: 'الرباط', region: 'الرباط-سلا-القنيطرة', images: 'https://images.unsplash.com/photo-1512917774080-791f6a3f2f95?w=400&h=300&fit=crop', status: 'active', viewsCount: 412, likesCount: 33, isFeatured: false, isUrgent: true, negotiation: true, delivery: false, createdAt: '2026-08-15T09:00:00Z', profile: p(9) },
  { id: 'l-78', title: 'رياض تقليدي في فاس للكراء', description: 'رياض تقليدي مرمم بالكامل 4 غرف وصالة وسطى مع نافورة. مناسب للإقامة السياحية أو كفضاء عمل. [DEMO]', price: 8000, currency: 'MAD', categoryId: 'c-realestate', condition: 'used', city: 'فاس', region: 'فاس-مكناس', images: 'https://images.unsplash.com/photo-1560518883-ce090597a0d0?w=400&h=300&fit=crop', status: 'active', viewsCount: 567, likesCount: 45, isFeatured: true, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-14T14:00:00Z', profile: p(4) },
  // Animals
  { id: 'l-79', title: 'قطط بريطانية قصيرة الشعر', description: 'ثلاثة قطط بريطانية قصيرة الشعر عمرها شهرين. مروضة ونظيفة مع شهادات صحية. لون رمادي أزرق. [DEMO]', price: 2000, currency: 'MAD', categoryId: 'c-animals', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop', status: 'active', viewsCount: 234, likesCount: 19, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-17T09:00:00Z', profile: p(1) },
  { id: 'l-80', title: 'كلب لابرادور ذكر 4 أشهر', description: 'جرو لابرادور ذكر لون شوكولاتة عمره 4 أشهر. مطعم وموجه صحيا مع جواز التلقيح. نشيط وودود مع الأطفال. [DEMO]', price: 3500, currency: 'MAD', categoryId: 'c-animals', condition: 'new', city: 'الرباط', region: 'الرباط-سلا-القنيطرة', images: 'https://images.unsplash.com/photo-1521791136064-7986c662921e?w=400&h=300&fit=crop', status: 'active', viewsCount: 189, likesCount: 15, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-16T11:00:00Z', profile: p(9) },
  // Hobbies
  { id: 'l-81', title: 'جيتار أكوستيك ياماها FG800', description: 'جيتار ياماها FG800 أكوستيك بلوط صلب. صوت رائع مناسب للمبتدئين والمحترفين. مع حقيبة غيتار وأوتار إضافية. [DEMO]', price: 2200, currency: 'MAD', categoryId: 'c-hobbies', condition: 'new', city: 'الدار البيضاء', region: 'الدار البيضاء-سطات', images: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop', status: 'active', viewsCount: 145, likesCount: 10, isFeatured: false, isUrgent: false, negotiation: true, delivery: true, createdAt: '2026-08-15T14:00:00Z', profile: p(7) },
  { id: 'l-82', title: 'طقم دراجات جبلية 2', description: 'طقم دراجتين جبليتين من ماركة شيمانو بمقاس 26 و28 بوصة. مناسبة للتنزه في الطبيعة. حالتهما ممتازة. [DEMO]', price: 3500, currency: 'MAD', categoryId: 'c-hobbies', condition: 'used', city: 'مراكش', region: 'مراكش-آسفي', images: 'https://images.unsplash.com/photo-1521791136064-7986c662921e?w=400&h=300&fit=crop', status: 'active', viewsCount: 112, likesCount: 8, isFeatured: false, isUrgent: false, negotiation: true, delivery: false, createdAt: '2026-08-14T09:00:00Z', profile: p(3) },
];

export const auctions = [
  { id: 'a-1', title: 'ساعة رولكس ديتونا أصلية', description: 'ساعة رولكس ديتونا من الفولاذ المقاوم للصدأ مع لوحة أرقام سوداء. موديل 2022 مع جميع الأوراق والضمان. [DEMO]', startPrice: 85000, currentBid: 127000, endsAt: '2026-08-22T20:00:00Z', images: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=300&fit=crop', bidCount: 23, status: 'active' },
  { id: 'a-2', title: 'لوحة زيتية لفنان مغربي مشهور', description: 'لوحة زيتية أصلية بريشة الفنان المغربي أحمد الشرقاوي. تمثل مشهد من حياة المدينة القديمة. [DEMO]', startPrice: 15000, currentBid: 28000, endsAt: '2026-08-21T18:00:00Z', images: 'https://images.unsplash.com/photo-1560518883-ce090597a0d0?w=400&h=300&fit=crop', bidCount: 15, status: 'active' },
  { id: 'a-3', title: 'طقم جواهر أميراتي فاخر', description: 'طقم جواهر يتضمن قلادة وأسورة وأقراط من الأحجار الكريمة المغربية مع إطار ذهب عيار 18. [DEMO]', startPrice: 25000, currentBid: 42000, endsAt: '2026-08-23T21:00:00Z', images: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop', bidCount: 18, status: 'active' },
  { id: 'a-4', title: 'سيارة كلاسيكية مرسيدس 1965', description: 'سيارة مرسيدس بنز W111 موديل 1965 بحالة ممتازة. تم ترميمها بالكامل مع المحرك الأصلي. قطعة استثنائية. [DEMO]', startPrice: 200000, currentBid: 350000, endsAt: '2026-08-25T20:00:00Z', images: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=400&h=300&fit=crop', bidCount: 8, status: 'active' },
  { id: 'a-5', title: 'مخطوطة قرآنية قديمة', description: 'مخطوطة قرآنية بخط مغربي أصلي عمرها أكثر من 300 سنة. محفوظة بحالة جيدة مع تجليد جلدي عتيق. [DEMO]', startPrice: 50000, currentBid: 89000, endsAt: '2026-08-24T19:00:00Z', images: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop', bidCount: 12, status: 'active' },
];

export const charityCases = [
  { id: 'ch-1', title: 'إعادة بناء مدرسة في الأطلس', description: 'مدرسة ابتدائية تضررت من الفيضانات تحتاج إعادة بناء كاملة لتستقبل 200 تلميذ. المبلغ يشمل البناء والتجهيز. [DEMO]', goalAmount: 500000, collectedAmount: 287000, urgency: 'critical', donors: 156, status: 'active' },
  { id: 'ch-2', title: 'عملية جراحية لطفلة', description: 'طفلة عمرها 4 سنوات تحتاج عملية جراحية عاجلة في القلب بتكلفة 120 ألف درهم. العائلة لا تستطيع تحمل التكاليف. [DEMO]', goalAmount: 120000, collectedAmount: 95000, urgency: 'high', donors: 89, status: 'active' },
  { id: 'ch-3', title: 'تزويد قرية نائية بالماء الصالح', description: 'قرية في جبال الأطلس تفتقر للماء الصالح للشرب. المشروع يهدف لحفر بئر وتركيب خزانات ونظام تنقية. [DEMO]', goalAmount: 300000, collectedAmount: 145000, urgency: 'high', donors: 112, status: 'active' },
  { id: 'ch-4', title: 'رعاية 50 يتيم', description: 'برنامج رعاية شاملة لـ 50 يتيما يشمل التعليم والملبس والغذاء على مدار سنة كاملة. [DEMO]', goalAmount: 250000, collectedAmount: 198000, urgency: 'medium', donors: 234, status: 'active' },
  { id: 'ch-5', title: 'زراعة 1000 شجرة زيتون', description: 'مشروع تشجير بمنطقة سوس لزراعة 1000 شجرة زيتون يوفر فرص عمل للشباب المحلي ويحارب التصحر. [DEMO]', goalAmount: 180000, collectedAmount: 67000, urgency: 'low', donors: 45, status: 'active' },
];

export const restaurants = [
  { id: 'r-1', name: 'مطعم دار يوسف', cuisine: 'مغربي تقليدي', rating: 4.8, deliveryTime: '30-45', minOrder: 50, city: 'الدار البيضاء', featured: true },
  { id: 'r-2', name: 'بيت الطاجين', cuisine: 'مغربي', rating: 4.6, deliveryTime: '35-50', minOrder: 40, city: 'مراكش', featured: true },
  { id: 'r-3', name: 'الحوت الذهبي', cuisine: 'مأكولات بحرية', rating: 4.9, deliveryTime: '25-40', minOrder: 80, city: 'الدار البيضاء', featured: true },
  { id: 'r-4', name: 'لو بيتي ريكادو', cuisine: 'مغربي فرنسي', rating: 4.7, deliveryTime: '40-55', minOrder: 60, city: 'الرباط', featured: false },
  { id: 'r-5', name: 'حلال بيتزا', cuisine: 'بيتزا وجبات سريعة', rating: 4.3, deliveryTime: '20-35', minOrder: 30, city: 'فاس', featured: false },
  { id: 'r-6', name: 'البربر', cuisine: 'مغربي أصيل', rating: 4.5, deliveryTime: '35-50', minOrder: 45, city: 'مراكش', featured: true },
  { id: 'r-7', name: 'شانديلير', cuisine: 'فرنسي عالمي', rating: 4.4, deliveryTime: '45-60', minOrder: 100, city: 'الدار البيضاء', featured: false },
  { id: 'r-8', name: 'سوشي طنجة', cuisine: 'ياباني', rating: 4.2, deliveryTime: '30-45', minOrder: 70, city: 'طنجة', featured: false },
  { id: 'r-9', name: 'النخلة', cuisine: 'مشرقي', rating: 4.6, deliveryTime: '25-40', minOrder: 35, city: 'أكادير', featured: false },
  { id: 'r-10', name: 'السلطان', cuisine: 'مغربي فاخر', rating: 4.8, deliveryTime: '40-55', minOrder: 90, city: 'الدار البيضاء', featured: true },
];

export const services = [
  { id: 's-1', title: 'تصوير أعراس وفيديو', provider: 'استوديو النور', category: 'تصوير', rating: 4.9, price: 5000, city: 'مراكش', area: 'مراكش', experience: '8 سنوات' },
  { id: 's-2', title: 'تنظيف منازل احترافي', provider: 'شركة النظافة البيضاء', category: 'تنظيف', rating: 4.7, price: 300, city: 'الدار البيضاء', area: 'الدار البيضاء', experience: '5 سنوات' },
  { id: 's-3', title: 'سباكة وصيانة', provider: 'فني الخبير', category: 'إصلاح', rating: 4.5, price: 200, city: 'الدار البيضاء', area: 'الدار البيضاء-سطات', experience: '12 سنة' },
  { id: 's-4', title: 'دروس خصوصية رياضيات', provider: 'أستاذ كريم', category: 'تعليم', rating: 4.8, price: 150, city: 'الرباط', area: 'الرباط', experience: '15 سنة' },
  { id: 's-5', title: 'تزيين أعراس وفعاليات', provider: 'دار الزينة', category: 'أعراس', rating: 4.6, price: 8000, city: 'الدار البيضاء', area: 'الدار البيضاء', experience: '6 سنوات' },
  { id: 's-6', title: 'تصميم جرافيك وهوية بصرية', provider: 'ميديا آرت', category: 'تقنية', rating: 4.7, price: 2500, city: 'الدار البيضاء', area: 'عن بعد', experience: '7 سنوات' },
  { id: 's-7', title: 'محاسبة وضريبة للمقاولات', provider: 'مكتب الأمانة', category: 'محاسبة', rating: 4.4, price: 1000, city: 'الرباط', area: 'الرباط-سلا-القنيطرة', experience: '10 سنوات' },
  { id: 's-8', title: 'فلاحة وحديقة', provider: 'بستاني الحديقة', category: 'خدمات منزلية', rating: 4.3, price: 250, city: 'مراكش', area: 'مراكش', experience: '20 سنة' },
  { id: 's-9', title: 'موسيقى لحفلات الأعراس', provider: 'فرقة النغم', category: 'موسيقى', rating: 4.8, price: 6000, city: 'فاس', area: 'فاس-مكناس', experience: '10 سنوات' },
  { id: 's-10', title: 'نجارة وأثاث مخصص', provider: 'نجار الصناع', category: 'حرف', rating: 4.6, price: 500, city: 'طنجة', area: 'طنجة', experience: '18 سنة' },
  { id: 's-11', title: 'دورات تدريبية في البرمجة', provider: 'أكاديمية كود', category: 'تعليم', rating: 4.5, price: 3000, city: 'الدار البيضاء', area: 'عن بعد', experience: '4 سنوات' },
  { id: 's-12', title: 'نقل أثاث وديكور', provider: 'شركة النقل السريع', category: 'نقل', rating: 4.2, price: 800, city: 'الدار البيضاء', area: 'الدار البيضاء', experience: '8 سنوات' },
  { id: 's-13', title: 'تصليح هواتف ذكية', provider: 'موبايل كير', category: 'إصلاح', rating: 4.4, price: 150, city: 'فاس', area: 'فاس', experience: '6 سنوات' },
  { id: 's-14', title: 'ترجمة معتمدة', provider: 'مكتب الترجمة', category: 'خدمات لغوية', rating: 4.7, price: 200, city: 'الرباط', area: 'الرباط', experience: '12 سنة' },
  { id: 's-15', title: 'رعاية الحيوانات الأليفة', provider: 'بيت الحيوان', category: 'حيوانات', rating: 4.8, price: 100, city: 'الدار البيضاء', area: 'الدار البيضاء', experience: '5 سنوات' },
];

export const jobs = [
  { id: 'j-1', title: 'مطور ويب Full-Stack', company: 'شركة سلطان تيك', type: 'fulltime', salary: '15000-25000 MAD', city: 'الدار البيضاء', requirements: 'React, Node.js, TypeScript, 3+ سنوات خبرة' },
  { id: 'j-2', title: 'مدير تسويق رقمي', company: 'أجنسية ديجيتال مارك', type: 'fulltime', salary: '18000-30000 MAD', city: 'مراكش', requirements: 'Google Ads, Social Media, SEO, 5+ سنوات' },
  { id: 'j-3', title: 'مصمم UI/UX', company: 'ستوديو كرييتيف', type: 'freelance', salary: '500-1000 MAD/يوم', city: 'عن بعد', requirements: 'Figma, Adobe XD, Portfolio قوي' },
  { id: 'j-4', title: 'محاسب أول', company: 'مكتب المحاسبة الحديث', type: 'fulltime', salary: '12000-18000 MAD', city: 'الرباط', requirements: 'بكالوريوس محاسبة, Excel, SAP, 3+ سنوات' },
  { id: 'j-5', title: 'ممثل خدمة عملاء', company: 'كول سنتر المغرب', type: 'fulltime', salary: '5000-7000 MAD', city: 'طنجة', requirements: 'عربي وفرنسية بطلاقة، مهارات تواصل جيدة' },
  { id: 'j-6', title: 'مطور تطبيقات موبايل', company: 'أبلاي تيك', type: 'remote', salary: '20000-35000 MAD', city: 'عن بعد', requirements: 'Flutter أو React Native, 2+ سنوات خبرة' },
  { id: 'j-7', title: 'كاتب محتوى', company: 'منصة المحتوى', type: 'freelance', salary: '300-600 MAD/مقال', city: 'عن بعد', requirements: 'كتابة إبداعية, عربي ممتاز, SEO أساسيات' },
  { id: 'j-8', title: 'مهندس شبكات', company: 'تيليكوم المغرب', type: 'fulltime', salary: '15000-22000 MAD', city: 'الدار البيضاء', requirements: 'CCNA, إدارة شبكات مؤسسية, 4+ سنوات' },
  { id: 'j-9', title: 'طبيب بيطري', company: 'عيادة الحيوان', type: 'parttime', salary: '200-400 MAD/ساعة', city: 'مراكش', requirements: 'دبلوم بيطرية, خبرة في علاج الحيوانات الأليفة' },
  { id: 'j-10', title: 'مدير مشروع IT', company: 'بنك المغرب', type: 'fulltime', salary: '25000-40000 MAD', city: 'الرباط', requirements: 'PMP, Agile, 7+ سنوات خبرة في إدارة المشاريع' },
];

export const newsArticles = [
  { id: 'n-1', title: 'المغرب يتصدر مؤشر النمو الاقتصادي في إفريقيا', excerpt: 'حقق المغرب معدل نمو اقتصادي بلغ 4.5% في الربع الأول من 2026 متفوقا على معظم الدول الإفريقية بفضل قطاعي السياحة والتصنيع. [DEMO]', source: 'المساء', date: '2026-08-19', category: 'اقتصاد' },
  { id: 'n-2', title: 'افتتاح خط قطار فائق السرعة بين طنجة وأكادير', excerpt: 'أعلنت وزارة النقل عن إطلاق المشروع التوسعي لخط الأفق عالي السرعة ليربط شمال المغرب بجنوبه عبر 6 محطات جديدة. [DEMO]', source: 'العلم', date: '2026-08-18', category: 'بنية تحتية' },
  { id: 'n-3', title: 'تطبيق مغربي يحصد جائزة أفضل تطبيق عربي', excerpt: 'فاز تطبيق سلطان بجائزة أفضل منصة رقمية عربية في مؤتمر ليبيكوم 2026 تقديرا لابتكاره في دمج التجارة والخدمات في منصة واحدة. [DEMO]', source: 'سايت إينفو', date: '2026-08-17', category: 'تكنولوجيا' },
  { id: 'n-4', title: 'مهرجان فاس للموسيقى العالمية في نسخته الـ 30', excerpt: 'يحتفل مهرجان فاس للموسيقى العالمية بالذكرى الثلاثين لانطلاقه مع مشاركة أكثر من 50 فنانا من مختلف أنحاء العالم في أجواء فنية فريدة. [DEMO]', source: 'Le360', date: '2026-08-16', category: 'ثقافة' },
  { id: 'n-5', title: 'ارتفاع الطلب على العقارات الفاخرة في الدار البيضاء بنسبة 25%', excerpt: 'شهد سوق العقارات الفاخرة بالدار البيضاء طفرة كبيرة في الطلب خلال النصف الأول من 2026 مدفوعا بالثقة في الاقتصاد الوطني. [DEMO]', source: 'هسبريس', date: '2026-08-15', category: 'عقارات' },
];

export const adminStats = {
  totalUsers: 48520,
  totalListings: 32150,
  activeUsers: 8920,
  todayListings: 342,
  totalRevenue: 2840000,
  monthlyGrowth: 12.5,
  activeAuctions: 28,
  pendingCashouts: 15,
  openTickets: 42,
  economyHealth: 94,
  totalCoins: 12500000,
  totalSupport: 4200000,
  totalCashouts: 1800000,
};

export const featureFlags = [
  { key: 'economy_enabled', value: true, label: 'نظام العملات', category: 'اقتصاد' },
  { key: 'support_enabled', value: true, label: 'زر الدعم', category: 'اقتصاد' },
  { key: 'rewards_enabled', value: true, label: 'نظام المكافآت', category: 'اقتصاد' },
  { key: 'cashout_enabled', value: true, label: 'السحب', category: 'مالية' },
  { key: 'zawaj_taaruf_enabled', value: true, label: 'الزواج والتعارف', category: 'اجتماعي' },
  { key: 'social_enabled', value: true, label: 'السوشيال', category: 'اجتماعي' },
  { key: 'live_streaming_enabled', value: false, label: 'البث المباشر', category: 'ترفيه' },
  { key: 'ar_vr_enabled', value: false, label: 'الواقع المعزز', category: 'تكنولوجيا' },
  { key: 'ai_assistant_enabled', value: true, label: 'المساعد الذكي', category: 'تكنولوجيا' },
  { key: 'blockchain_enabled', value: false, label: 'البلوكتشين', category: 'تكنولوجيا' },
  { key: 'grants_enabled', value: true, label: 'المنح', category: 'فرص' },
  { key: 'challenges_enabled', value: true, label: 'التحديات', category: 'فرص' },
  { key: 'bounties_enabled', value: true, label: 'المكافآت', category: 'فرص' },
  { key: 'tasks_enabled', value: true, label: 'المهام الصغيرة', category: 'فرص' },
  { key: 'growth_campaigns_enabled', value: true, label: 'حملات النمو', category: 'تسويق' },
  { key: 'news_rewards_enabled', value: false, label: 'مكافآت الأخبار', category: 'محتوى' },
  { key: 'business_boost_enabled', value: true, label: 'تعزيز الأعمال', category: 'تسويق' },
  { key: 'diaspora_enabled', value: true, label: 'الجالية المغربية', category: 'توسع' },
];

export const walletHistory = [
  { id: 'w-1', type: 'purchase', amount: 500, currency: 'SC', description: 'شراء عملات سلطان', date: '2026-08-19', status: 'completed' },
  { id: 'w-2', type: 'support', amount: -100, currency: 'SC', description: 'دعم @fatima_zahra', date: '2026-08-18', status: 'completed' },
  { id: 'w-3', type: 'reward', amount: 50, currency: 'SR', description: 'مكافأة نشر إعلان مميز', date: '2026-08-17', status: 'completed' },
  { id: 'w-4', type: 'support_received', amount: 200, currency: 'SC', description: 'دعم من @karim_m', date: '2026-08-16', status: 'completed' },
  { id: 'w-5', type: 'cashout', amount: -500, currency: 'SR', description: 'طلب سحب إلى الحساب البنكي', date: '2026-08-15', status: 'pending' },
  { id: 'w-6', type: 'boost', amount: -50, currency: 'SC', description: 'تعزيز إعلان: آيفون 15 برو ماكس', date: '2026-08-14', status: 'completed' },
  { id: 'w-7', type: 'reward', amount: 25, currency: 'SR', description: 'مكافأة إكمال الملف الشخصي', date: '2026-08-13', status: 'completed' },
  { id: 'w-8', type: 'support', amount: -50, currency: 'SC', description: 'دعم حالة تضامن: إعادة بناء مدرسة', date: '2026-08-12', status: 'completed' },
];
