// ═══════════════════════════════════════════════════════════════════════════════
// SULTAN AI OS — Agent Registry — All 13 AI Employees
// ═══════════════════════════════════════════════════════════════════════════════

import type { AgentDefinition, PermissionAction, PermissionLevel } from './types';

const basePermissions: Record<PermissionAction, PermissionLevel> = {
  read: 'allowed',
  write: 'approval_required',
  execute: 'approval_required',
  deploy: 'denied',
  delete: 'denied',
  database: 'approval_required',
  github: 'approval_required',
  cloudflare: 'denied',
  social: 'denied',
  finance: 'denied',
  user_data: 'approval_required',
  secrets: 'denied',
};

export const AGENT_DEFINITIONS: AgentDefinition[] = [
  {
    id: 'agent-master',
    name: 'Master Agent',
    nameAr: 'الوكيل الرئيسي',
    description: 'The primary orchestrator that understands commands, delegates to specialized agents, and coordinates complex multi-step tasks across the entire platform.',
    descriptionAr: 'المنسق الرئيسي الذي يفهم الأوامر ويوزع المهام على الوكلاء المتخصصين وينسق المهام المعقدة متعددة الخطوات في المنصة بأكملها.',
    icon: 'Crown',
    category: 'core',
    capabilities: ['command_understanding', 'task_decomposition', 'agent_orchestration', 'delegation', 'parallel_execution', 'context_management', 'result_synthesis'],
    defaultModel: 'gpt-4o',
    permissions: {
      ...basePermissions,
      read: 'allowed',
      execute: 'allowed',
      database: 'allowed',
      github: 'allowed',
      cloudflare: 'allowed',
    },
    maxConcurrentTasks: 10,
    timeoutMs: 300000,
    isAlwaysOn: true,
    tools: ['chat', 'search', 'delegate', 'knowledge_query', 'memory_store', 'memory_retrieve', 'task_create', 'task_update', 'workflow_start'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'agent-engineering',
    name: 'Engineering Agent',
    nameAr: 'وكيل الهندسة',
    description: 'Handles code analysis, generation, refactoring, bug fixing, and technical implementation tasks. Works with the codebase directly.',
    descriptionAr: 'يتولى تحليل الكود وإنشائه وإعادة هيكلته وإصلاح الأخطاء والمهام التقنية. يعمل مباشرة مع قاعدة الكود.',
    icon: 'Code2',
    category: 'engineering',
    capabilities: ['code_analysis', 'code_generation', 'refactoring', 'bug_fixing', 'code_review', 'technical_documentation', 'architecture_analysis'],
    defaultModel: 'claude-sonnet-4-20250514',
    permissions: {
      ...basePermissions,
      read: 'allowed',
      write: 'approval_required',
      execute: 'approval_required',
      github: 'approval_required',
    },
    maxConcurrentTasks: 5,
    timeoutMs: 600000,
    isAlwaysOn: false,
    tools: ['github_read', 'github_write', 'github_pr', 'code_analyze', 'code_generate', 'code_fix', 'search', 'knowledge_query'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'agent-qa',
    name: 'QA Agent',
    nameAr: 'وكيل الجودة',
    description: 'Performs quality assurance, testing, validation, and verification of features, code changes, and system behavior.',
    descriptionAr: 'يقوم بضمان الجودة والاختبار والتحقق من صحة الميزات وتغييرات الكود وسلوك النظام.',
    icon: 'CheckCircle2',
    category: 'quality',
    capabilities: ['test_planning', 'test_execution', 'bug_detection', 'regression_testing', 'performance_testing', 'accessibility_testing', 'test_report_generation'],
    defaultModel: 'gpt-4o',
    permissions: {
      ...basePermissions,
      read: 'allowed',
      execute: 'allowed',
      database: 'read',
    },
    maxConcurrentTasks: 5,
    timeoutMs: 300000,
    isAlwaysOn: false,
    tools: ['test_run', 'test_analyze', 'code_analyze', 'github_read', 'search', 'knowledge_query', 'report_generate'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'agent-security',
    name: 'Security Agent',
    nameAr: 'وكيل الأمن',
    description: 'Monitors, audits, and enforces security policies. Scans for vulnerabilities, reviews access controls, and ensures compliance.',
    descriptionAr: 'يراقب ويدقق وينفذ سياسات الأمان. يفحص الثغرات ويراجع ضوابط الوصول ويضمن الامتثال.',
    icon: 'ShieldCheck',
    category: 'security',
    capabilities: ['vulnerability_scanning', 'access_control_review', 'security_audit', 'rls_analysis', 'dependency_audit', 'incident_analysis', 'security_reporting'],
    defaultModel: 'claude-sonnet-4-20250514',
    permissions: {
      ...basePermissions,
      read: 'allowed',
      database: 'allowed',
      github: 'allowed',
    },
    maxConcurrentTasks: 3,
    timeoutMs: 300000,
    isAlwaysOn: false,
    tools: ['security_scan', 'rls_audit', 'dependency_check', 'access_review', 'github_read', 'supabase_inspect', 'knowledge_query', 'report_generate'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'agent-devops',
    name: 'DevOps Agent',
    nameAr: 'وكيل العمليات',
    description: 'Manages deployments, CI/CD, infrastructure, monitoring, and build processes. Integrates with GitHub and Cloudflare.',
    descriptionAr: 'يدير عمليات النشر والبنية التحتية والمراقبة وعمليات البناء. يتكامل مع GitHub و Cloudflare.',
    icon: 'Server',
    category: 'devops',
    capabilities: ['deployment_management', 'build_analysis', 'infrastructure_monitoring', 'rollback_management', 'log_analysis', 'performance_monitoring', 'environment_management'],
    defaultModel: 'gpt-4o',
    permissions: {
      ...basePermissions,
      read: 'allowed',
      execute: 'approval_required',
      deploy: 'approval_required',
      github: 'allowed',
      cloudflare: 'allowed',
    },
    maxConcurrentTasks: 3,
    timeoutMs: 600000,
    isAlwaysOn: false,
    tools: ['github_read', 'github_write', 'cloudflare_deploy', 'cloudflare_logs', 'cloudflare_status', 'build_analyze', 'log_analyze', 'knowledge_query'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'agent-research',
    name: 'Research Agent',
    nameAr: 'وكيل البحث',
    description: 'Conducts web research, competitive analysis, technology evaluation, and market research to support decision-making.',
    descriptionAr: 'يقوم بأبحاث الويب وتحليل المنافسين وتقييم التقنيات وأبحاث السوق لدعم اتخاذ القرار.',
    icon: 'Microscope',
    category: 'research',
    capabilities: ['web_research', 'competitive_analysis', 'technology_evaluation', 'market_research', 'trend_analysis', 'data_gathering', 'report_generation'],
    defaultModel: 'gpt-4o',
    permissions: {
      ...basePermissions,
      read: 'allowed',
      execute: 'allowed',
    },
    maxConcurrentTasks: 5,
    timeoutMs: 300000,
    isAlwaysOn: false,
    tools: ['web_search', 'web_read', 'browser_navigate', 'browser_read', 'knowledge_store', 'knowledge_query', 'report_generate', 'search'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'agent-data',
    name: 'Data/Analytics Agent',
    nameAr: 'وكيل البيانات والتحليلات',
    description: 'Analyzes platform data, generates insights, creates reports, and supports data-driven decision-making across the platform.',
    descriptionAr: 'يحلل بيانات المنصة وينتج رؤى وينشئ التقارير ويدعم اتخاذ القرارات المبنية على البيانات.',
    icon: 'BarChart3',
    category: 'data',
    capabilities: ['data_analysis', 'statistical_analysis', 'trend_detection', 'anomaly_detection', 'report_generation', 'dashboard_data', 'query_optimization'],
    defaultModel: 'gpt-4o',
    permissions: {
      ...basePermissions,
      read: 'allowed',
      database: 'allowed',
    },
    maxConcurrentTasks: 5,
    timeoutMs: 300000,
    isAlwaysOn: false,
    tools: ['database_query', 'data_analyze', 'chart_generate', 'report_generate', 'knowledge_store', 'knowledge_query', 'search'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'agent-product',
    name: 'Product Agent',
    nameAr: 'وكيل المنتج',
    description: 'Manages product features, user stories, prioritization, and product strategy. Analyzes user feedback and market needs.',
    descriptionAr: 'يدير ميزات المنتج وقصص المستخدمين والأولويات واستراتيجية المنتج. يحلل ملاحظات المستخدمين واحتياجات السوق.',
    icon: 'Package',
    category: 'product',
    capabilities: ['feature_planning', 'user_story_creation', 'prioritization', 'feedback_analysis', 'roadmap_management', 'competitive_analysis', 'specification_writing'],
    defaultModel: 'gpt-4o',
    permissions: {
      ...basePermissions,
      read: 'allowed',
    },
    maxConcurrentTasks: 3,
    timeoutMs: 300000,
    isAlwaysOn: false,
    tools: ['knowledge_store', 'knowledge_query', 'web_search', 'data_analyze', 'report_generate', 'search'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'agent-growth',
    name: 'Growth Agent',
    nameAr: 'وكيل النمو',
    description: 'Focuses on user acquisition, retention, engagement strategies, and growth experiments to expand the platform.',
    descriptionAr: 'يركز على اكتساب المستخدمين والاحتفاظ بهم واستراتيجيات التفاعل وتجارب النمو لتوسيع المنصة.',
    icon: 'TrendingUp',
    category: 'growth',
    capabilities: ['growth_analysis', 'funnel_optimization', 'retention_analysis', 'experiment_design', 'cohort_analysis', 'viral_analysis', 'growth_reporting'],
    defaultModel: 'gpt-4o',
    permissions: {
      ...basePermissions,
      read: 'allowed',
      database: 'allowed',
    },
    maxConcurrentTasks: 3,
    timeoutMs: 300000,
    isAlwaysOn: false,
    tools: ['data_analyze', 'database_query', 'knowledge_store', 'knowledge_query', 'report_generate', 'search'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'agent-social',
    name: 'Social Agent',
    nameAr: 'وكيل التواصل الاجتماعي',
    description: 'Manages official social media accounts, content planning, engagement, and community management on behalf of Sultan.',
    descriptionAr: 'يدير حسابات التواصل الاجتماعي الرسمية والتخطيط للمحتوى والتفاعل وإدارة المجتمع باسم سلطان.',
    icon: 'Share2',
    category: 'social',
    capabilities: ['content_planning', 'post_creation', 'engagement_monitoring', 'trend_detection', 'community_management', 'analytics_reporting', 'campaign_planning'],
    defaultModel: 'gpt-4o',
    permissions: {
      ...basePermissions,
      read: 'allowed',
      write: 'approval_required',
      social: 'approval_required',
      execute: 'allowed',
    },
    maxConcurrentTasks: 3,
    timeoutMs: 300000,
    isAlwaysOn: false,
    tools: ['social_post', 'social_analyze', 'web_search', 'trend_detect', 'knowledge_store', 'knowledge_query', 'report_generate'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'agent-content',
    name: 'Content Agent',
    nameAr: 'وكيل المحتوى',
    description: 'Creates, reviews, and manages content across the platform including news, articles, product descriptions, and marketing copy.',
    descriptionAr: 'ينشئ ويراجع ويدير المحتوى في جميع أنحاء المنصة بما في ذلك الأخبار والمقالات وأوصاف المنتجات والنصوص التسويقية.',
    icon: 'FileText',
    category: 'content',
    capabilities: ['content_creation', 'content_review', 'copywriting', 'translation', 'summarization', 'seo_optimization', 'content_calendar'],
    defaultModel: 'gpt-4o',
    permissions: {
      ...basePermissions,
      read: 'allowed',
      write: 'approval_required',
    },
    maxConcurrentTasks: 5,
    timeoutMs: 300000,
    isAlwaysOn: false,
    tools: ['knowledge_store', 'knowledge_query', 'web_search', 'search', 'report_generate', 'content_create', 'content_review'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'agent-business',
    name: 'Business Agent',
    nameAr: 'وكيل الأعمال',
    description: 'Supports business owners with analytics, content suggestions, offer optimization, demand discovery, and customer service assistance.',
    descriptionAr: 'يدعم أصحاب الأعمال بالتحليلات واقتراحات المحتوى وتحسين العروض واكتشاف الطلب ومساعدة خدمة العملاء.',
    icon: 'Briefcase',
    category: 'business',
    capabilities: ['business_analytics', 'demand_analysis', 'pricing_optimization', 'customer_insights', 'offer_suggestions', 'content_advice', 'revenue_analysis'],
    defaultModel: 'gpt-4o',
    permissions: {
      ...basePermissions,
      read: 'allowed',
      database: 'allowed',
    },
    maxConcurrentTasks: 5,
    timeoutMs: 300000,
    isAlwaysOn: false,
    tools: ['data_analyze', 'database_query', 'knowledge_store', 'knowledge_query', 'search', 'report_generate'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'agent-knowledge',
    name: 'Knowledge Agent',
    nameAr: 'وكيل المعرفة',
    description: 'Manages the organizational knowledge base, maintains documentation, indexes information, and ensures knowledge is accessible to all agents.',
    descriptionAr: 'يدير قاعدة المعرفة التنظيمية ويحافظ على الوثائق ويؤرشف المعلومات ويضمن إتاحة المعرفة لجميع الوكلاء.',
    icon: 'BookOpen',
    category: 'knowledge',
    capabilities: ['knowledge_management', 'documentation_maintenance', 'information_indexing', 'knowledge_retrieval', 'knowledge_synthesis', 'taxonomy_management', 'knowledge_gaps_detection'],
    defaultModel: 'gpt-4o',
    permissions: {
      ...basePermissions,
      read: 'allowed',
      write: 'allowed',
      database: 'allowed',
    },
    maxConcurrentTasks: 5,
    timeoutMs: 300000,
    isAlwaysOn: false,
    tools: ['knowledge_store', 'knowledge_query', 'knowledge_index', 'knowledge_synthesize', 'search', 'web_search', 'report_generate'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export function getAgentDefinition(agentId: string): AgentDefinition | undefined {
  return AGENT_DEFINITIONS.find(a => a.id === agentId);
}

export function getAgentsByCategory(category: string): AgentDefinition[] {
  return AGENT_DEFINITIONS.filter(a => a.category === category);
}

export function getAgentForTask(taskType: string): AgentDefinition {
  const taskAgentMap: Record<string, string> = {
    code_analysis: 'agent-engineering',
    code_generation: 'agent-engineering',
    bug_fixing: 'agent-engineering',
    testing: 'agent-qa',
    security_audit: 'agent-security',
    deployment: 'agent-devops',
    web_research: 'agent-research',
    data_analysis: 'agent-data',
    product_planning: 'agent-product',
    growth_analysis: 'agent-growth',
    social_media: 'agent-social',
    content_creation: 'agent-content',
    business_analysis: 'agent-business',
    knowledge_management: 'agent-knowledge',
  };
  const agentId = taskAgentMap[taskType] || 'agent-master';
  return getAgentDefinition(agentId) || AGENT_DEFINITIONS[0];
}
