name: Test Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: work/sultan-platform
    steps:
      - run: echo hello
